modLoader="javafml"
loaderVersion="[61,)"
license="MIT"
[[mods]]
modId="simplehammers"
version="1.0.5"
displayName="Simple Hammers"
authors="JustErikSK, Satorisek, With Rage Studios"
description='''Mine faster and wider with Simple Hammers that break 3x3 areas of blocks at once.'''
[[dependencies.simplehammers]]
    modId="forge"
    mandatory=true
    versionRange="[61,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplehammers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11,1.22,)"
    ordering="NONE"
    side="BOTH"
