modLoader="javafml"
loaderVersion="[63,)"
license="MIT"
[[mods]]
modId="simplehammers"
version="1.0.5"
displayName="Simple Hammers"
authors="JustErikSK, Satorisek, With Rage Studios"
description='''Mine faster and wider with Simple Hammers that break 3x3 areas of blocks at once.'''
[[dependencies.simplehammers]]
    modId="forge"
    mandatory=true
    versionRange="[63,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplehammers]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.1,26.2,)"
    ordering="NONE"
    side="BOTH"
